# Generated by Django 5.2.7 on 2025-10-05 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_remove_networknode_address_networknode_city_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networknode",
            options={"verbose_name": "Узел сети", "verbose_name_plural": "Узлы сети"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.RemoveField(
            model_name="product",
            name="available",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="node",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="model",
            field=models.CharField(
                default="Не указано", max_length=255, verbose_name="Модель"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="network_node",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="network.networknode",
                verbose_name="Узел сети",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="release_date",
            field=models.DateField(
                default="2025-01-01", verbose_name="Дата выхода на рынок"
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="city",
            field=models.CharField(
                default="Не указано", max_length=100, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="country",
            field=models.CharField(
                default="Не указано", max_length=100, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Задолженность",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="email",
            field=models.EmailField(
                default="no-email@example.com", max_length=254, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="house_number",
            field=models.CharField(
                default="0", max_length=20, verbose_name="Номер дома"
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="name",
            field=models.CharField(
                default="Без названия", max_length=255, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="street",
            field=models.CharField(
                default="Не указано", max_length=100, verbose_name="Улица"
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="network.networknode",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                default="Без названия", max_length=255, verbose_name="Название продукта"
            ),
        ),
    ]
