# Generated by Django 5.2.7 on 2025-10-05 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_alter_networknode_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True, verbose_name="В наличии"),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="country",
            field=models.CharField(max_length=100, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="debt",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Задолженность"
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="house_number",
            field=models.CharField(max_length=20, verbose_name="Номер дома"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="street",
            field=models.CharField(max_length=100, verbose_name="Улица"),
        ),
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.CharField(max_length=255, verbose_name="Модель"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название продукта"),
        ),
        migrations.AlterField(
            model_name="product",
            name="network_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="network.networknode",
                verbose_name="Узел сети",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateField(verbose_name="Дата выхода на рынок"),
        ),
    ]
