# Generated by Django 5.2.7 on 2025-10-05 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_product_available_product_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Время создания",
            ),
            preserve_default=False,
        ),
    ]
