# Generated by Django 5.2.7 on 2025-10-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_alter_networknode_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networknode",
            name="country",
            field=models.CharField(
                choices=[
                    ("RU", "Россия"),
                    ("UA", "Украина"),
                    ("BY", "Беларусь"),
                    ("KZ", "Казахстан"),
                    ("GE", "Грузия"),
                    ("AM", "Армения"),
                ],
                max_length=20,
                verbose_name="Страна",
            ),
        ),
    ]
