# Generated by Django 5.2.7 on 2025-10-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_alter_networknode_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="networknode",
            name="role",
            field=models.CharField(
                choices=[
                    ("factory", "Завод"),
                    ("retail", "Розничная сеть"),
                    ("individual", "Индивидуальный предприниматель"),
                ],
                default="retail",
                max_length=20,
                verbose_name="Тип узла",
            ),
        ),
    ]
