# Generated by Django 5.2.7 on 2025-10-05 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0009_networknode_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networknode",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="network.networknode",
                verbose_name="Поставщик (предыдущий по иерархии объект сети)",
            ),
        ),
    ]
