# Generated by Django 5.2.7 on 2025-10-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0010_alter_networknode_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networknode",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
    ]
